#pragma once

#include <string>
#include <unordered_map>

#include "tju_local_planning/common/macros.h"

TJU_LOCAL_PLANNING_LIB_COMMON_NAMESPACE_BEGIN

enum ErrorCode : uint32_t {
  SUCCESS = 0,
  // 基础错误 [1-9]
  FUNCTION_NOT_IMPLEMENTED = 1,  ///< 函数未实现
  PARAMETER_ERROR = 2,           ///< 参数错误
  UNINITIALIZED = 3,             ///< 未正确初始化
  YAML_CONFIG_ERROR = 4,         ///< YAML配置文件错误
  
  // 数据缓存错误 [10-29]
  DATA_BUFFER_ROLLBACK = 10,                       ///< 数据回滚
  DATA_BUFFER_EXTRACT_FAILED_FOR_EMPTY = 11,       ///< 数据为空导致提取失败
  DATA_BUFFER_EXTRACT_FAILED_FOR_TIMEOUT = 12,     ///< 数据超时导致提取失败

  // 传感器错误 [30-49]
  SENSOR_DATA_TYPE_NOT_FOUND = 30,                 ///< 传感器数据类型未找到
  
  // 局部路径规划错误 [300-349]
  LOCAL_PLANNING_UNINITIALIZED = 300,           ///< 局部路径规划未初始化
  LOCAL_PLANNING_CONFIG_ERROR = 301,            ///< 局部路径规划配置错误
  LOCAL_PLANNING_LOAD_CONFIG_FAILED = 302,      ///< 加载局部路径规划配置失败
  LOCAL_PLANNING_PARAMETER_ERROR = 303,         ///< 局部路径规划参数错误
  LOCAL_PLANNING_INPUT_DATA_INVALID = 304,      ///< 局部路径规划输入数据无效
  LOCAL_PLANNING_APP_USE_QUINTICPOLYNOMIALPLANNER = 305, /// APP调用五次多项式失败
  LOCAL_PLANNING_REFERENCE_LINE_ERROR = 306,    ///< 参考线错误
  LOCAL_PLANNING_OBSTACLE_DATA_ERROR = 307,     ///< 障碍物数据错误
  LOCAL_PLANNING_VEHICLE_STATE_ERROR = 308,     ///< 车辆状态错误
  LOCAL_PLANNING_TRAJECTORY_GENERATION_FAILED = 309, ///< 轨迹生成失败
  LOCAL_PLANNING_OPTIMIZATION_FAILED = 310,     ///< 优化失败
  LOCAL_PLANNING_COLLISION_DETECTED = 311,      ///< 检测到碰撞风险
  LOCAL_PLANNING_KINEMATIC_INFEASIBLE = 312,    ///< 运动学不可行
  LOCAL_PLANNING_DYNAMIC_INFEASIBLE = 313,      ///< 动力学不可行
  LOCAL_PLANNING_TIMEOUT = 314,                 ///< 计算超时
  LOCAL_PLANNING_MAP_ERROR = 315,               ///< 地图数据错误
  LOCAL_PLANNING_TRAFFIC_RULE_VIOLATION = 316,  ///< 违反交通规则
  LOCAL_PLANNING_EMERGENCY_STOP_TRIGGERED = 317, ///< 触发紧急停车
  LOCAL_PLANNING_PATH_FOLLOWING_ERROR = 318,    ///< 路径跟随错误
  LOCAL_PLANNING_SPEED_PROFILE_ERROR = 319,     ///< 速度曲线错误
  LOCAL_PLANNING_PREDICTION_ERROR = 320,        ///< 预测错误
  LOCAL_PLANNING_DECISION_ERROR = 321,          ///< 决策错误
  LOCAL_PLANNING_COST_EVALUATION_ERROR = 322,   ///< 代价评估错误
  LOCAL_PLANNING_BOUNDARY_CONSTRAINT_ERROR = 323, ///< 边界约束错误
  LOCAL_PLANNING_EMPTY_TRAJECTORY = 324,          ///< 轨迹为空
  LOCAL_PLANNING_NEAREST_POINT_ERROR = 325,       ///< 最近点查找失败
  LOCAL_PLANNING_TRAJECTORY_MATCH_ERROR = 326,    ///< 轨迹匹配失败
  LOCAL_PLANNING_INDEX_OUT_OF_BOUNDS = 327,       ///< 轨迹索引越界错误
};

static const std::unordered_map<ErrorCode, std::string> error_code_to_string = {
    {ErrorCode::SUCCESS, "SUCCESS"},
    {ErrorCode::FUNCTION_NOT_IMPLEMENTED, "FUNCTION_NOT_IMPLEMENTED"},
    {ErrorCode::PARAMETER_ERROR, "PARAMETER_ERROR"},
    {ErrorCode::UNINITIALIZED, "UNINITIALIZED"},
    {ErrorCode::YAML_CONFIG_ERROR, "YAML_CONFIG_ERROR"},
    
    // 数据缓存错误
    {ErrorCode::DATA_BUFFER_ROLLBACK, "DATA_BUFFER_ROLLBACK"},
    {ErrorCode::DATA_BUFFER_EXTRACT_FAILED_FOR_EMPTY, "DATA_BUFFER_EXTRACT_FAILED_FOR_EMPTY"},
    {ErrorCode::DATA_BUFFER_EXTRACT_FAILED_FOR_TIMEOUT, "DATA_BUFFER_EXTRACT_FAILED_FOR_TIMEOUT"},

    // 传感器错误
    {ErrorCode::SENSOR_DATA_TYPE_NOT_FOUND, "SENSOR_DATA_TYPE_NOT_FOUND"},
    
    // 局部路径规划错误
    {ErrorCode::LOCAL_PLANNING_UNINITIALIZED, "LOCAL_PLANNING_UNINITIALIZED"},
    {ErrorCode::LOCAL_PLANNING_CONFIG_ERROR, "LOCAL_PLANNING_CONFIG_ERROR"},
    {ErrorCode::LOCAL_PLANNING_LOAD_CONFIG_FAILED, "LOCAL_PLANNING_LOAD_CONFIG_FAILED"},
    {ErrorCode::LOCAL_PLANNING_PARAMETER_ERROR, "LOCAL_PLANNING_PARAMETER_ERROR"},
    {ErrorCode::LOCAL_PLANNING_INPUT_DATA_INVALID, "LOCAL_PLANNING_INPUT_DATA_INVALID"},
    {ErrorCode::LOCAL_PLANNING_APP_USE_QUINTICPOLYNOMIALPLANNER, "LOCAL_PLANNING_APP_USE_QUINTICPOLYNOMIALPLANNER"},
    {ErrorCode::LOCAL_PLANNING_REFERENCE_LINE_ERROR, "LOCAL_PLANNING_REFERENCE_LINE_ERROR"},
    {ErrorCode::LOCAL_PLANNING_OBSTACLE_DATA_ERROR, "LOCAL_PLANNING_OBSTACLE_DATA_ERROR"},
    {ErrorCode::LOCAL_PLANNING_VEHICLE_STATE_ERROR, "LOCAL_PLANNING_VEHICLE_STATE_ERROR"},
    {ErrorCode::LOCAL_PLANNING_TRAJECTORY_GENERATION_FAILED, "LOCAL_PLANNING_TRAJECTORY_GENERATION_FAILED"},
    {ErrorCode::LOCAL_PLANNING_OPTIMIZATION_FAILED, "LOCAL_PLANNING_OPTIMIZATION_FAILED"},
    {ErrorCode::LOCAL_PLANNING_COLLISION_DETECTED, "LOCAL_PLANNING_COLLISION_DETECTED"},
    {ErrorCode::LOCAL_PLANNING_KINEMATIC_INFEASIBLE, "LOCAL_PLANNING_KINEMATIC_INFEASIBLE"},
    {ErrorCode::LOCAL_PLANNING_DYNAMIC_INFEASIBLE, "LOCAL_PLANNING_DYNAMIC_INFEASIBLE"},
    {ErrorCode::LOCAL_PLANNING_TIMEOUT, "LOCAL_PLANNING_TIMEOUT"},
    {ErrorCode::LOCAL_PLANNING_MAP_ERROR, "LOCAL_PLANNING_MAP_ERROR"},
    {ErrorCode::LOCAL_PLANNING_TRAFFIC_RULE_VIOLATION, "LOCAL_PLANNING_TRAFFIC_RULE_VIOLATION"},
    {ErrorCode::LOCAL_PLANNING_EMERGENCY_STOP_TRIGGERED, "LOCAL_PLANNING_EMERGENCY_STOP_TRIGGERED"},
    {ErrorCode::LOCAL_PLANNING_PATH_FOLLOWING_ERROR, "LOCAL_PLANNING_PATH_FOLLOWING_ERROR"},
    {ErrorCode::LOCAL_PLANNING_SPEED_PROFILE_ERROR, "LOCAL_PLANNING_SPEED_PROFILE_ERROR"},
    {ErrorCode::LOCAL_PLANNING_PREDICTION_ERROR, "LOCAL_PLANNING_PREDICTION_ERROR"},
    {ErrorCode::LOCAL_PLANNING_DECISION_ERROR, "LOCAL_PLANNING_DECISION_ERROR"},
    {ErrorCode::LOCAL_PLANNING_COST_EVALUATION_ERROR, "LOCAL_PLANNING_COST_EVALUATION_ERROR"},
    {ErrorCode::LOCAL_PLANNING_BOUNDARY_CONSTRAINT_ERROR, "LOCAL_PLANNING_BOUNDARY_CONSTRAINT_ERROR"},
    {ErrorCode::LOCAL_PLANNING_EMPTY_TRAJECTORY, "LOCAL_PLANNING_EMPTY_TRAJECTORY"},
    {ErrorCode::LOCAL_PLANNING_NEAREST_POINT_ERROR, "LOCAL_PLANNING_NEAREST_POINT_ERROR"},
    {ErrorCode::LOCAL_PLANNING_TRAJECTORY_MATCH_ERROR, "LOCAL_PLANNING_TRAJECTORY_MATCH_ERROR"},
    {ErrorCode::LOCAL_PLANNING_INDEX_OUT_OF_BOUNDS, "LOCAL_PLANNING_INDEX_OUT_OF_BOUNDS"},
};


[[__maybe_unused__]] static std::string get_error_code_string(const ErrorCode& error_code) {
  return error_code_to_string.at(error_code);
}

TJU_LOCAL_PLANNING_LIB_COMMON_NAMESPACE_END
