/**
 * @file code.h
 * @author WangXu (xuwang_note@hotmail.com)
 * @brief 错误码
 * @version 0.1
 * @date 2024-09-18
 *
 * @copyright Copyright (c) 2024
 *
 */

#pragma once

#include <string>
#include <unordered_map>

#include "trunk_perception/common/macros.h"

TRUNK_PERCEPTION_LIB_COMMON_NAMESPACE_BEGIN

enum ErrorCode : uint32_t {
  SUCCESS = 0,
  // 基础错误 [1-9]
  FUNCTION_NOT_IMPLEMENTED = 1,  ///< 函数未实现
  PARAMETER_ERROR = 2,           ///< 参数错误
  UNINITIALIZED = 3,             ///< 未正确初始化
  YAML_CONFIG_ERROR = 4,         ///< YAML配置文件错误
  // 数据缓冲区错误 [10-19]
  DATA_BUFFER_ROLLBACK = 10,
  DATA_BUFFER_EXTRACT_FAILED_FOR_EMPTY = 11,
  DATA_BUFFER_EXTRACT_FAILED_FOR_TIMEOUT = 12,
  // 传感器错误 [20-29]
  SENSOR_DATA_TYPE_NOT_FOUND = 20,
  SENSOR_POSE_NOT_FOUND = 21,
  POINT_CLOUD_INVALID = 22,
  IMAGE_DATA_INVALID = 23,
  ODOMETRY_DATA_INVALID = 24,
  // Object Detection Lidar 错误 [30-39]
  LIDAR_NET_SDK_INIT_FAILED = 30,
  LIDAR_GROUND_DETECTION_FAILED = 31,
  LIDAR_OD_FRAME_NOT_FOUND = 32,
  // 车道线检测错误 [40-49]
  LANE_DETECTOR_INIT_CAMERA_PARAMS_FAILED = 40,
  LANE_DETECTOR_SDK_INIT_FAILED = 41,
  LANE_DETECTOR_SDK_INFER_FAILED = 42,
  // 车道线跟踪错误 [50-59]
  LANE_TRACKER_INIT_FAILED = 50,
  LANE_TRACKER_ODOMETRY_NOT_FOUND = 51,
  LANE_TRACKER_LD_FRAME_NOT_FOUND = 52,
  // 后融合任务 [60-69]
  TARGET_FUSION_INIT_FAILED = 60,
  TARGET_FUSION_INIT_LOAD_CONFIG_FAILED = 61,
  TARGET_FUSION_INIT_TRACKER_MANAGER_FAILED = 62,
  TARGET_FUSION_GET_DATA_LIDAR_OD_FRAME_FAILED = 63,
  TARGET_FUSION_GET_DATA_FRONT_RADAR_FAILED = 64,
  TARGET_FUSION_GET_DATA_FRONT_RADAR_POSE_FAILED = 65,
  TARGET_FUSION_GET_DATA_ODOMETRY_FAILED = 66,
  TARGET_FUSION_GET_DATA_FRONT_VISION_FAILED = 67,
  TARGET_FUSION_GET_DATA_SIDE_VISION_FAILED = 68,
  // 前向视觉检测错误[70-79]
  FRONT_VISION_DETECTOR_INIT_CAMERA_PARAMS_FAILED = 70,
  FRONT_VISION_DETECTOR_SDK_INIT_FAILED = 71,
  FRONT_VISION_DETECTOR_SDK_INFER_FAILED = 72,
  FOD_VISION_FRAME_NOT_FOUND = 73,
  // Object Detection 错误 [80-89]
  OD_SPARSE4D_INIT_FAILED = 80,
  OD_SPARSE4D_DETECT_FAILED = 81,
  OD_MMSPARSE4D_INIT_FAILED = 82,
  OD_MMSPARSE4D_DETECT_FAILED = 83,
  // 后融合中获取角毫米波数据任务 [90-99]                   // @author zzg 2025-01-06
  TARGET_FUSION_GET_DATA_CORNER_RADAR1_FAILED = 90,
  TARGET_FUSION_GET_DATA_CORNER_RADAR1_POSE_FAILED = 91,
  TARGET_FUSION_GET_DATA_CORNER_RADAR5_FAILED = 92,
  TARGET_FUSION_GET_DATA_CORNER_RADAR5_POSE_FAILED = 93,
  TARGET_FUSION_GET_DATA_CORNER_RADAR7_FAILED = 94,
  TARGET_FUSION_GET_DATA_CORNER_RADAR7_POSE_FAILED = 95,
  TARGET_FUSION_GET_DATA_CORNER_RADAR11_FAILED = 96,
  TARGET_FUSION_GET_DATA_CORNER_RADAR11_POSE_FAILED = 97,
};

static const std::unordered_map<ErrorCode, std::string> error_code_to_string = {
    {ErrorCode::SUCCESS, "SUCCESS"},
    {ErrorCode::FUNCTION_NOT_IMPLEMENTED, "FUNCTION_NOT_IMPLEMENTED"},
    {ErrorCode::PARAMETER_ERROR, "PARAMETER_ERROR"},
    {ErrorCode::UNINITIALIZED, "UNINITIALIZED"},
    {ErrorCode::YAML_CONFIG_ERROR, "YAML_CONFIG_ERROR"},
    {ErrorCode::DATA_BUFFER_ROLLBACK, "DATA_BUFFER_ROLLBACK"},
    {ErrorCode::DATA_BUFFER_EXTRACT_FAILED_FOR_EMPTY, "DATA_BUFFER_EXTRACT_FAILED_FOR_EMPTY"},
    {ErrorCode::DATA_BUFFER_EXTRACT_FAILED_FOR_TIMEOUT, "DATA_BUFFER_EXTRACT_FAILED_FOR_TIMEOUT"},
    {ErrorCode::SENSOR_DATA_TYPE_NOT_FOUND, "SENSOR_DATA_TYPE_NOT_FOUND"},
    {ErrorCode::SENSOR_POSE_NOT_FOUND, "SENSOR_POSE_NOT_FOUND"},
    {ErrorCode::POINT_CLOUD_INVALID, "POINT_CLOUD_INVALID"},
    {ErrorCode::IMAGE_DATA_INVALID, "IMAGE_DATA_INVALID"},
    {ErrorCode::LIDAR_NET_SDK_INIT_FAILED, "LIDAR_NET_SDK_INIT_FAILED"},
    {ErrorCode::LANE_DETECTOR_INIT_CAMERA_PARAMS_FAILED, "LANE_DETECTOR_INIT_CAMERA_PARAMS_FAILED"},
    {ErrorCode::LANE_DETECTOR_SDK_INIT_FAILED, "LANE_DETECTOR_SDK_INIT_FAILED"},
    {ErrorCode::LANE_DETECTOR_SDK_INFER_FAILED, "LANE_DETECTOR_SDK_INFER_FAILED"},
    {ErrorCode::LANE_TRACKER_INIT_FAILED, "LANE_TRACKER_INIT_FAILED"},
    {ErrorCode::LANE_TRACKER_ODOMETRY_NOT_FOUND, "LANE_TRACKER_ODOMETRY_NOT_FOUND"},
    {ErrorCode::TARGET_FUSION_INIT_FAILED, "TARGET_FUSION_INIT_FAILED"},
    {ErrorCode::TARGET_FUSION_INIT_LOAD_CONFIG_FAILED, "TARGET_FUSION_INIT_LOAD_CONFIG_FAILED"},
    {ErrorCode::TARGET_FUSION_INIT_TRACKER_MANAGER_FAILED, "TARGET_FUSION_INIT_TRACKER_MANAGER_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_LIDAR_OD_FRAME_FAILED, "TARGET_FUSION_GET_DATA_LIDAR_OD_FRAME_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_FRONT_RADAR_FAILED, "TARGET_FUSION_GET_DATA_FRONT_RADAR_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_FRONT_RADAR_POSE_FAILED, "TARGET_FUSION_GET_DATA_FRONT_RADAR_POSE_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_ODOMETRY_FAILED, "TARGET_FUSION_GET_DATA_ODOMETRY_FAILED"},
    {ErrorCode::OD_SPARSE4D_INIT_FAILED, "OD_SPARSE4D_INIT_FAILED"},
    {ErrorCode::OD_SPARSE4D_DETECT_FAILED, "OD_SPARSE4D_DETECT_FAILED"},
    {ErrorCode::OD_MMSPARSE4D_INIT_FAILED, "OD_MMSPARSE4D_INIT_FAILED"},
    {ErrorCode::OD_MMSPARSE4D_DETECT_FAILED, "OD_MMSPARSE4D_DETECT_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_FRONT_VISION_FAILED, "TARGET_FUSION_GET_DATA_FRONT_VISION_FAILED"},
    {ErrorCode::FRONT_VISION_DETECTOR_INIT_CAMERA_PARAMS_FAILED, "FRONT_VISION_DETECTOR_INIT_CAMERA_PARAMS_FAILED"},
    {ErrorCode::FRONT_VISION_DETECTOR_SDK_INIT_FAILED, "FRONT_VISION_DETECTOR_SDK_INIT_FAILED"},
    {ErrorCode::FRONT_VISION_DETECTOR_SDK_INFER_FAILED, "FRONT_VISION_DETECTOR_SDK_INFER_FAILED"},
    {ErrorCode::FOD_VISION_FRAME_NOT_FOUND, "FOD_VISION_FRAME_NOT_FOUND"},
    {ErrorCode::TARGET_FUSION_GET_DATA_CORNER_RADAR1_FAILED, "TARGET_FUSION_GET_DATA_CORNER_RADAR1_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_CORNER_RADAR1_POSE_FAILED, "TARGET_FUSION_GET_DATA_CORNER_RADAR1_POSE_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_CORNER_RADAR5_FAILED, "TARGET_FUSION_GET_DATA_CORNER_RADAR5_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_CORNER_RADAR5_POSE_FAILED, "TARGET_FUSION_GET_DATA_CORNER_RADAR5_POSE_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_CORNER_RADAR7_FAILED, "TARGET_FUSION_GET_DATA_CORNER_RADAR7_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_CORNER_RADAR7_POSE_FAILED, "TARGET_FUSION_GET_DATA_CORNER_RADAR7_POSE_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_CORNER_RADAR11_FAILED, "TARGET_FUSION_GET_DATA_CORNER_RADAR11_FAILED"},
    {ErrorCode::TARGET_FUSION_GET_DATA_CORNER_RADAR11_POSE_FAILED, "TARGET_FUSION_GET_DATA_CORNER_RADAR11_POSE_FAILED"},
};

[[__maybe_unused__]] static std::string get_error_code_string(const ErrorCode& error_code) {
  return error_code_to_string.at(error_code);
}

TRUNK_PERCEPTION_LIB_COMMON_NAMESPACE_END