# opencv
if (${PLATFORM} STREQUAL "orin")
  message("--- OpenCV searching for version 4.5 on ${PLATFORM}")
  find_package(OpenCV 4.5 REQUIRED)
  set(OpenCV_LIBS libopencv_calib3d.so.4.5;libopencv_core.so.4.5;libopencv_dnn.so.4.5;libopencv_features2d.so.4.5;libopencv_flann.so.4.5;libopencv_gapi.so.4.5;libopencv_highgui.so.4.5;libopencv_imgcodecs.so.4.5;libopencv_imgproc.so.4.5;libopencv_ml.so.4.5;libopencv_objdetect.so.4.5;libopencv_photo.so.4.5;libopencv_stitching.so.4.5;libopencv_video.so.4.5;libopencv_videoio.so.4.5)
  set(OpenCV_LIBRARIES ${OpenCV_LIBS})
else()
  # 如果是focal或jammy，则使用opencv4.2
  if (${OS_CODENAME} STREQUAL "focal" OR ${OS_CODENAME} STREQUAL "jammy")
      message("--- OpenCV searching for version 4.2 on ${PLATFORM}")
      find_package(OpenCV 4.2 REQUIRED)
  else()
      message("--- OpenCV searching for version 3.3 on ${PLATFORM}")
      find_package(OpenCV 3 REQUIRED)
  endif()
endif()
message(STATUS "OpenCV version: ${OpenCV_VERSION}")
include_directories(${OpenCV_INCLUDE_DIRS})
message(STATUS "OpenCV_LIBS ${OpenCV_LIBS}")
message(STATUS "OpenCV_LIBRARIES ${OpenCV_LIBRARIES}")