if (${sdk_lidarnetsdk_enable})
    find_package(LidarNetSdk EXACT ${sdk_lidarnetsdk_version} REQUIRED)
    message(STATUS "LidarNetSdk version: ${LidarNetSdk_VERSION}")
    message(STATUS "LidarNetSdk libraries: ${LidarNetSdk_LIBRARIES}")
    message(STATUS "LidarNetSdk include dirs: ${LidarNetSdk_INCLUDE_DIRS}")
    include_directories(${LidarNetSdk_INCLUDE_DIRS})
endif()

if (${sdkbevlaneconedethighway_enable})
    find_package(sdkbevlaneconedethighway EXACT ${sdkbevlaneconedethighway_version} REQUIRED)
    message(STATUS "SdkBevLaneConeDet libraries: ${SDKBevLaneConeDetHighway_LIBRARIES}")
    message(STATUS "SdkBevLaneConeDet include dirs: ${SDKBevLaneConeDetHighway_INCLUDE_DIRS}")
    message(STATUS "SdkBevLaneConeDet library dirs: ${SDKBevLaneConeDetHighway_LIBRARY_DIRS}")
    include_directories(${SDKBevLaneConeDetHighway_INCLUDE_DIRS})
    link_directories(${SDKBevLaneConeDetHighway_LIBRARY_DIRS})
endif()
