if (${sdk_lidarnetsdk_enable})
    find_package(LidarNetSdk EXACT ${sdk_lidarnetsdk_version} REQUIRED)
    message(STATUS "LidarNetSdk version: ${LidarNetSdk_VERSION}")
    message(STATUS "LidarNetSdk libraries: ${LidarNetSdk_LIBRARIES}")
    message(STATUS "LidarNetSdk include dirs: ${LidarNetSdk_INCLUDE_DIRS}")
    include_directories(${LidarNetSdk_INCLUDE_DIRS})
endif()

if (${sdkbevlaneconedethighway_enable})
    find_package(sdkbevlaneconedethighway EXACT ${sdkbevlaneconedethighway_version} REQUIRED)
    message(STATUS "SdkBevLaneConeDet libraries: ${SDKBevLaneConeDetHighway_LIBRARIES}")
    message(STATUS "SdkBevLaneConeDet include dirs: ${SDKBevLaneConeDetHighway_INCLUDE_DIRS}")
    message(STATUS "SdkBevLaneConeDet library dirs: ${SDKBevLaneConeDetHighway_LIBRARY_DIRS}")
    include_directories(${SDKBevLaneConeDetHighway_INCLUDE_DIRS})
    link_directories(${SDKBevLaneConeDetHighway_LIBRARY_DIRS})
endif()

if (${detectionnetsdk_enable})
    find_package(DetectionNetSDK EXACT ${detectionnetsdk_version} REQUIRED)
    message(STATUS "DetectionNetSdk version: ${DetectionNetSDK_VERSION}")
    message(STATUS "DetectionNetSdk libraries: ${DetectionNetSDK_LIBRARIES}")
    message(STATUS "DetectionNetSdk include dirs: ${DetectionNetSDK_INCLUDE_DIRS}")
    include_directories(${DetectionNetSDK_INCLUDE_DIRS})
    link_directories(${DetectionNetSDK_LIBRARY_DIRS})
endif()

if (${sdkvisdetr3ddconffront_enable})
    find_package(sdkvisdetr3ddconffront EXACT ${sdkvisdetr3ddconffront_version} REQUIRED)
    message(STATUS "SDKVisDetR3DDconfFront libraries: ${SDKVisDetR3DDconfFront_LIBRARIES}")
    message(STATUS "SDKVisDetR3DDconfFront include dirs: ${SDKVisDetR3DDconfFront_INCLUDE_DIRS}")
    message(STATUS "SDKVisDetR3DDconfFront library dirs: ${SDKVisDetR3DDconfFront_LIBRARY_DIRS}")
    include_directories(${SDKVisDetR3DDconfFront_INCLUDE_DIRS})
    link_directories(${SDKVisDetR3DDconfFront_LIBRARY_DIRS})
endif()